name: eco_city
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: lib/assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Montserrat-Black.ttf
          weight: 900
